### ISSUE TITLE
Failed to load nodelet '/oak` of type `depthai_ros_driver/Camera` to manager `oak_nodelet_manager'

### ISSUE THREAD

**Issue by Embedded1993** [luxonis/depthai-ros#263]
OS: butuntu 20.04 Raspeberry Pi 4
ROS: ros-noetic-depthai-ros

I installed ros from bianary.

So I'm going to run rtabmap slam on ros1

But I'm getting this error
![image](https://user-images.githubusercontent.com/98973485/228141175-0d188885-c543-4aeb-8453-29c723916e19.png)

**Comment by Serafadam** [comment]
Hi, for bug reports it would be best to describe issue as mentioned in the [bug template](https://github.com/luxonis/depthai-ros/blob/humble/.github/ISSUE_TEMPLATE/bug_report.md), though not all debugging options are currently available for Noetic.
One other question that might help here - do you have `rtabmap-ros` package installed?

**Comment by Embedded1993** [comment]
Yes. I have installed rtabmap-ros

**Comment by Serafadam** [comment]
Could you paste what package version you have? 
`apt show ros-$ROS_DISTRO-depthai ros-$ROS_DISTRO-depthai-ros ros-$ROS_DISTRO-depthai-bridge ros-$ROS_DISTRO-depthai-ros-msgs ros-$ROS_DISTRO-depthai-ros-driver`

**Comment by Embedded1993** [comment]
ubuntu@ubuntu:~$ apt show ros-noetic-depthai ros-noetic-depthai-ros ros-noetic-depthai-bridge ros-noetic-depthai-ros-msgs ros-noetic-depthai-ros-driver
Package: ros-noetic-depthai
Version: 2.20.2-1focal.20230202.200823
Priority: optional
Section: misc
Maintainer: Sachin Guruswamy <sachin@luxonis.com>
Installed-Size: 21.3 MB
Depends: libc6 (>= 2.17), libgcc-s1 (>= 4.5), libopencv-core4.2 (>= 4.2.0+dfsg), libopencv-imgproc4.2 (>= 4.2.0+dfsg), libstdc++6 (>= 9), libopencv-dev, libusb-1.0-0-dev, nlohmann-json3-dev, ros-noetic-catkin
Homepage: https://www.luxonis.com/
Download-Size: 10.2 MB
APT-Manual-Installed: no
APT-Sources: http://packages.ros.org/ros/ubuntu focal/main arm64 Packages
Description: DepthAI core is a C++ library which comes with firmware and an API to interact with OAK Platform

Package: ros-noetic-depthai-ros
Version: 2.6.1-2focal.20230225.012112
Priority: optional
Section: misc
Maintainer: sachin <sachin@luxonis.com>
Installed-Size: 18.4 kB
Depends: ros-noetic-depthai, ros-noetic-depthai-bridge, ros-noetic-depthai-examples, ros-noetic-depthai-ros-driver, ros-noetic-depthai-ros-msgs
Download-Size: 2124 B
APT-Manual-Installed: yes
APT-Sources: http://packages.ros.org/ros/ubuntu focal/main arm64 Packages
Description: The depthai-ros package

Package: ros-noetic-depthai-bridge
Version: 2.6.1-2focal.20230216.065040
Priority: optional
Section: misc
Maintainer: Sachin Guruswamy <sachin@luxonis.com>
Installed-Size: 69.5 MB
Depends: libc6 (>= 2.17), libgcc-s1 (>= 4.2), libopencv-core4.2 (>= 4.2.0+dfsg), libopencv-imgcodecs4.2 (>= 4.2.0+dfsg), libopencv-imgproc4.2 (>= 4.2.0+dfsg), libstdc++6 (>= 9), libboost-dev, libopencv-dev, ros-noetic-camera-info-manager, ros-noetic-cv-bridge, ros-noetic-depthai, ros-noetic-depthai-ros-msgs, ros-noetic-image-transport, ros-noetic-robot-state-publisher, ros-noetic-ros-environment, ros-noetic-roscpp, ros-noetic-sensor-msgs, ros-noetic-std-msgs, ros-noetic-stereo-msgs, ros-noetic-vision-msgs, ros-noetic-xacro
Download-Size: 10.5 MB
APT-Manual-Installed: no
APT-Sources: http://packages.ros.org/ros/ubuntu focal/main arm64 Packages
Description: The depthai_bridge package

Package: ros-noetic-depthai-ros-msgs
Version: 2.6.1-2focal.20230216.064856
Priority: optional
Section: misc
Maintainer: Sachin Guruswamy <sachin@luxonis.com>
Installed-Size: 475 kB
Depends: ros-noetic-geometry-msgs, ros-noetic-message-runtime, ros-noetic-sensor-msgs, ros-noetic-std-msgs, ros-noetic-vision-msgs
Download-Size: 39.4 kB
APT-Manual-Installed: no
APT-Sources: http://packages.ros.org/ros/ubuntu focal/main arm64 Packages
Description: Package to keep interface independent of the driver

Package: ros-noetic-depthai-ros-driver
Version: 2.6.1-2focal.20230225.010515
Priority: optional
Section: misc
Maintainer: Adam Serafin <adam.serafin@luxonis.com>
Installed-Size: 1490 kB
Depends: libc6 (>= 2.17), libconsole-bridge0.4, libgcc-s1 (>= 4.2), libopencv-core4.2 (>= 4.2.0+dfsg), libopencv-imgproc4.2 (>= 4.2.0+dfsg), libstdc++6 (>= 5.2), ros-noetic-camera-info-manager, ros-noetic-cv-bridge, ros-noetic-depthai, ros-noetic-depthai-bridge, ros-noetic-diagnostic-msgs, ros-noetic-dynamic-reconfigure, ros-noetic-image-pipeline, ros-noetic-image-transport, ros-noetic-image-transport-plugins, ros-noetic-message-filters, ros-noetic-nodelet, ros-noetic-roscpp, ros-noetic-rospy, ros-noetic-sensor-msgs, ros-noetic-std-msgs, ros-noetic-std-srvs, ros-noetic-vision-msgs
Download-Size: 277 kB
APT-Manual-Installed: no
APT-Sources: http://packages.ros.org/ros/ubuntu focal/main arm64 Packages
Description: Depthai ROS Monolithic node.

**Comment by Embedded1993** [comment]
same issue when I run it.
roslaunch depthai_ros_driver camera.launch
But works this
roslaunch depthai_examples stereo_inertial_node.launch

**Comment by Serafadam** [comment]
Ok, got it, it seems like newest version of packages wasn't added to latest noetic sync. If you don't want to wait, you could either build packages from source switch to testing repository to download latest packages.
To do that, edit `/etc/apt/sources.list.d/ros1-latest.list` and change `ros` to `ros-testing`

**Comment by Embedded1993** [comment]
I can't find testing repository.
And I tried to build from source. But it crashed at 66% and frozen screen 
![image](https://user-images.githubusercontent.com/98973485/228308874-a7cf3fcd-93d6-43a1-8419-bfd34e219bf3.png)

**Comment by Embedded1993** [comment]
> Ok, got it, it seems like newest version of packages wasn't added to latest noetic sync. If you don't want to wait, you could either build packages from source switch to testing repository to download latest packages. To do that, edit `/etc/apt/sources.list.d/ros1-latest.list` and change `ros` to `ros-testing`

Please let me know

**Comment by Serafadam** [comment]
This might be due to limited resources, you can[ limit resource usage when building](https://answers.ros.org/question/59031/how-do-i-limit-the-number-of-cores-used-in-the-build-process-by-catkin/). Additionally, you can use docker to get container with the latest released version
`xhost +local:docker`
`docker run -it -v /dev/:/dev/ --network host --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix luxonis/depthai-ros:noetic-latest`
Note, you'll need to install rtabmap in docker separately, since the image contains minimum dependencies.

**Comment by Embedded1993** [comment]
I built success from source. But I'm getting these warnings.

ubuntu@ubuntu:~/work/dai_ws$ roslaunch rtabmap_ros rgbd_mapping.launch
... logging to /home/ubuntu/.ros/log/b733bd48-ce38-11ed-9b40-9dd08eea8197/roslaunch-ubuntu-6737.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:36687/

SUMMARY
========

CLEAR PARAMETERS
 * /rtabmap/rgbd_odometry/
 * /rtabmap/rtabmap/
 * /rtabmap/rtabmapviz/

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /rtabmap/rgbd_odometry/approx_sync: True
 * /rtabmap/rgbd_odometry/approx_sync_max_interval: 0.0
 * /rtabmap/rgbd_odometry/config_path: 
 * /rtabmap/rgbd_odometry/expected_update_rate: 0.0
 * /rtabmap/rgbd_odometry/frame_id: camera_link
 * /rtabmap/rgbd_odometry/ground_truth_base_frame_id: 
 * /rtabmap/rgbd_odometry/ground_truth_frame_id: 
 * /rtabmap/rgbd_odometry/guess_frame_id: 
 * /rtabmap/rgbd_odometry/guess_min_rotation: 0.0
 * /rtabmap/rgbd_odometry/guess_min_translation: 0.0
 * /rtabmap/rgbd_odometry/keep_color: False
 * /rtabmap/rgbd_odometry/max_update_rate: 0.0
 * /rtabmap/rgbd_odometry/odom_frame_id: /odom
 * /rtabmap/rgbd_odometry/publish_tf: True
 * /rtabmap/rgbd_odometry/queue_size: 10
 * /rtabmap/rgbd_odometry/subscribe_rgbd: False
 * /rtabmap/rgbd_odometry/wait_for_transform_duration: 0.2
 * /rtabmap/rgbd_odometry/wait_imu_to_init: False
 * /rtabmap/rtabmap/Mem/IncrementalMemory: true
 * /rtabmap/rtabmap/Mem/InitWMWithAllNodes: false
 * /rtabmap/rtabmap/approx_sync: True
 * /rtabmap/rtabmap/config_path: 
 * /rtabmap/rtabmap/database_path: ~/.ros/rtabmap.db
 * /rtabmap/rtabmap/frame_id: camera_link
 * /rtabmap/rtabmap/gen_depth: False
 * /rtabmap/rtabmap/gen_depth_decimation: 1
 * /rtabmap/rtabmap/gen_depth_fill_holes_error: 0.1
 * /rtabmap/rtabmap/gen_depth_fill_holes_size: 0
 * /rtabmap/rtabmap/gen_depth_fill_iterations: 1
 * /rtabmap/rtabmap/gen_scan: False
 * /rtabmap/rtabmap/ground_truth_base_frame_id: 
 * /rtabmap/rtabmap/ground_truth_frame_id: 
 * /rtabmap/rtabmap/initial_pose: 
 * /rtabmap/rtabmap/landmark_angular_variance: 9999.0
 * /rtabmap/rtabmap/landmark_linear_variance: 0.0001
 * /rtabmap/rtabmap/map_frame_id: map
 * /rtabmap/rtabmap/odom_frame_id: 
 * /rtabmap/rtabmap/odom_frame_id_init: 
 * /rtabmap/rtabmap/odom_sensor_sync: False
 * /rtabmap/rtabmap/odom_tf_angular_variance: 0.001
 * /rtabmap/rtabmap/odom_tf_linear_variance: 0.001
 * /rtabmap/rtabmap/publish_tf: True
 * /rtabmap/rtabmap/queue_size: 10
 * /rtabmap/rtabmap/scan_cloud_max_points: 0
 * /rtabmap/rtabmap/subscribe_depth: True
 * /rtabmap/rtabmap/subscribe_odom_info: True
 * /rtabmap/rtabmap/subscribe_rgb: True
 * /rtabmap/rtabmap/subscribe_rgbd: False
 * /rtabmap/rtabmap/subscribe_scan: False
 * /rtabmap/rtabmap/subscribe_scan_cloud: False
 * /rtabmap/rtabmap/subscribe_scan_descriptor: False
 * /rtabmap/rtabmap/subscribe_stereo: False
 * /rtabmap/rtabmap/subscribe_user_data: False
 * /rtabmap/rtabmap/wait_for_transform_duration: 0.2
 * /rtabmap/rtabmapviz/approx_sync: True
 * /rtabmap/rtabmapviz/frame_id: camera_link
 * /rtabmap/rtabmapviz/odom_frame_id: 
 * /rtabmap/rtabmapviz/queue_size: 10
 * /rtabmap/rtabmapviz/subscribe_depth: True
 * /rtabmap/rtabmapviz/subscribe_odom_info: True
 * /rtabmap/rtabmapviz/subscribe_rgb: True
 * /rtabmap/rtabmapviz/subscribe_rgbd: False
 * /rtabmap/rtabmapviz/subscribe_scan: False
 * /rtabmap/rtabmapviz/subscribe_scan_cloud: False
 * /rtabmap/rtabmapviz/subscribe_scan_descriptor: False
 * /rtabmap/rtabmapviz/subscribe_stereo: False
 * /rtabmap/rtabmapviz/wait_for_transform_duration: 0.2

NODES
  /rtabmap/
    rgbd_odometry (rtabmap_ros/rgbd_odometry)
    rtabmap (rtabmap_ros/rtabmap)
    rtabmapviz (rtabmap_ros/rtabmapviz)

auto-starting new master
process[master]: started with pid [6748]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b733bd48-ce38-11ed-9b40-9dd08eea8197
process[rosout-1]: started with pid [6761]
started core service [/rosout]
process[rtabmap/rgbd_odometry-2]: started with pid [6769]
process[rtabmap/rtabmap-3]: started with pid [6770]
process[rtabmap/rtabmapviz-4]: started with pid [6771]
[ INFO] [1680097856.763821583]: Starting node...
[ INFO] [1680097856.962528376]: Initializing nodelet with 4 worker threads.
[ INFO] [1680097857.004336780]: Initializing nodelet with 4 worker threads.
[ INFO] [1680097857.936043606]: Odometry: frame_id               = camera_link
[ INFO] [1680097857.936295512]: Odometry: odom_frame_id          = /odom
[ INFO] [1680097857.936471121]: Odometry: publish_tf             = true
[ INFO] [1680097857.937197819]: Odometry: wait_for_transform     = true
[ INFO] [1680097857.940886324]: Odometry: wait_for_transform_duration  = 0.200000
[ INFO] [1680097857.942946770]: Odometry: log_to_rosout_level    = 4
[ INFO] [1680097857.944898883]: Odometry: initial_pose           = xyz=0.000000,0.000000,0.000000 rpy=0.000000,-0.000000,0.000000
[ INFO] [1680097857.945222195]: Odometry: ground_truth_frame_id  = 
[ INFO] [1680097857.945483341]: Odometry: ground_truth_base_frame_id = 
[ INFO] [1680097857.945972429]: Odometry: config_path            = 
[ INFO] [1680097857.946097632]: Odometry: publish_null_when_lost = true
[ INFO] [1680097857.946208353]: Odometry: guess_frame_id         = 
[ INFO] [1680097857.946290890]: Odometry: guess_min_translation  = 0.000000
[ INFO] [1680097857.946371333]: Odometry: guess_min_rotation     = 0.000000
[ INFO] [1680097857.946435296]: Odometry: guess_min_time         = 0.000000
[ INFO] [1680097857.946496943]: Odometry: expected_update_rate   = 0.000000 Hz
[ INFO] [1680097857.946574776]: Odometry: max_update_rate        = 0.000000 Hz
[ INFO] [1680097857.946637072]: Odometry: min_update_rate        = 0.000000 Hz
[ INFO] [1680097857.946690238]: Odometry: wait_imu_to_init       = false
[ INFO] [1680097857.946794034]: Odometry: stereoParams_=0 visParams_=1 icpParams_=0
[ INFO] [1680097858.078606118]: /rtabmap/rtabmap(maps): map_filter_radius          = 0.000000
[ INFO] [1680097858.078760320]: /rtabmap/rtabmap(maps): map_filter_angle           = 30.000000
[ INFO] [1680097858.078856745]: /rtabmap/rtabmap(maps): map_cleanup                = true
[ INFO] [1680097858.078911300]: /rtabmap/rtabmap(maps): map_always_update          = false
[ INFO] [1680097858.078962726]: /rtabmap/rtabmap(maps): map_empty_ray_tracing      = true
[ INFO] [1680097858.079027632]: /rtabmap/rtabmap(maps): cloud_output_voxelized     = true
[ INFO] [1680097858.079108391]: /rtabmap/rtabmap(maps): cloud_subtract_filtering   = false
[ INFO] [1680097858.079194316]: /rtabmap/rtabmap(maps): cloud_subtract_filtering_min_neighbors = 2
[ INFO] [1680097858.082424770]: /rtabmap/rtabmap(maps): octomap_tree_depth         = 16
[ INFO] [1680097858.142823461]: Starting node...
[ INFO] [1680097858.423959962]: rtabmap: frame_id      = camera_link
[ INFO] [1680097858.424170849]: rtabmap: map_frame_id  = map
[ INFO] [1680097858.426076259]: rtabmap: log_to_rosout_level = 4
[ INFO] [1680097858.427064324]: rtabmap: initial_pose  = 
[ INFO] [1680097858.428361776]: rtabmap: use_action_for_goal  = false
[ INFO] [1680097858.429541655]: rtabmap: tf_delay      = 0.050000
[ INFO] [1680097858.430524851]: rtabmap: tf_tolerance  = 0.100000
[ INFO] [1680097858.432122133]: rtabmap: odom_sensor_sync   = false
[ INFO] [1680097858.439132833]: rtabmap: gen_scan  = false
[ INFO] [1680097858.441402573]: rtabmap: gen_depth  = false
[ INFO] [1680097859.301747766]: rtabmapviz: Using configuration from "/home/ubuntu/.ros/rtabmap_gui.ini"
[ INFO] [1680097860.387812134]: Setting RTAB-Map parameter "Mem/IncrementalMemory"="true"
[ INFO] [1680097860.394850926]: Setting RTAB-Map parameter "Mem/InitWMWithAllNodes"="false"
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[ INFO] [1680097862.909463222]: RGBDOdometry: approx_sync    = true
[ INFO] [1680097862.909623610]: RGBDOdometry: approx_sync_max_interval = 0.000000
[ INFO] [1680097862.909706554]: RGBDOdometry: queue_size     = 10
[ INFO] [1680097862.909779572]: RGBDOdometry: subscribe_rgbd = false
[ INFO] [1680097862.909855515]: RGBDOdometry: rgbd_cameras   = 1
[ INFO] [1680097862.909931385]: RGBDOdometry: keep_color     = false
[ INFO] [1680097863.016392481]: 
/rtabmap/rgbd_odometry subscribed to (approx sync):
   /camera/rgb/image_rect_color \
   /camera/depth_registered/image_raw \
   /camera/rgb/camera_info
[ INFO] [1680097863.766175412]: rtabmapviz: Reading parameters from the ROS server...
[ INFO] [1680097863.769033740]: rtabmapviz: Cannot get rtabmap's parameters, waiting max 5 seconds in case the node has just been launched.
[ INFO] [1680097864.276177324]: RTAB-Map detection rate = 1.000000 Hz
[ INFO] [1680097864.278920393]: rtabmap: Using database from "/home/ubuntu/.ros/rtabmap.db" (0 MB).
[ INFO] [1680097864.317766489]: rtabmap: Database version = "0.20.23".
[ INFO] [1680097864.318134338]: rtabmap: SLAM mode (Mem/IncrementalMemory=true)
[ INFO] [1680097864.454470180]: /rtabmap/rtabmap: subscribe_depth = true
[ INFO] [1680097864.454614679]: /rtabmap/rtabmap: subscribe_rgb = true
[ INFO] [1680097864.454740548]: /rtabmap/rtabmap: subscribe_stereo = false
[ INFO] [1680097864.454825974]: /rtabmap/rtabmap: subscribe_rgbd = false (rgbd_cameras=1)
[ INFO] [1680097864.454943695]: /rtabmap/rtabmap: subscribe_odom_info = true
[ INFO] [1680097864.455024620]: /rtabmap/rtabmap: subscribe_user_data = false
[ INFO] [1680097864.455096897]: /rtabmap/rtabmap: subscribe_scan = false
[ INFO] [1680097864.455190415]: /rtabmap/rtabmap: subscribe_scan_cloud = false
[ INFO] [1680097864.455261026]: /rtabmap/rtabmap: subscribe_scan_descriptor = false
[ INFO] [1680097864.455365895]: /rtabmap/rtabmap: queue_size    = 10
[ INFO] [1680097864.455467561]: /rtabmap/rtabmap: approx_sync   = true
[ INFO] [1680097864.455726614]: Setup depth callback
[ INFO] [1680097864.555190788]: 
/rtabmap/rtabmap subscribed to (approx sync):
   /odom \
   /camera/rgb/image_rect_color \
   /camera/depth_registered/image_raw \
   /camera/rgb/camera_info \
   /rtabmap/odom_info
[ INFO] [1680097865.777284360]: rtabmap 0.20.23 started...
[ INFO] [1680097866.127715570]: rtabmapviz: rtabmap's parameters seem now there! continuing...
[ INFO] [1680097867.193935818]: rtabmapviz: Parameters read = 359
[ INFO] [1680097867.194093187]: rtabmapviz: Parameters successfully read.
[ WARN] [1680097868.017046148]: /rtabmap/rgbd_odometry: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. 
/rtabmap/rgbd_odometry subscribed to (approx sync):
   /camera/rgb/image_rect_color \
   /camera/depth_registered/image_raw \
   /camera/rgb/camera_info
[ INFO] [1680097868.449702736]: /rtabmap/rtabmapviz: subscribe_depth = true
[ INFO] [1680097868.449994289]: /rtabmap/rtabmapviz: subscribe_rgb = true
[ INFO] [1680097868.450188935]: /rtabmap/rtabmapviz: subscribe_stereo = false
[ INFO] [1680097868.450344434]: /rtabmap/rtabmapviz: subscribe_rgbd = false (rgbd_cameras=1)
[ INFO] [1680097868.451308222]: /rtabmap/rtabmapviz: subscribe_odom_info = true
[ INFO] [1680097868.451712200]: /rtabmap/rtabmapviz: subscribe_user_data = false
[ INFO] [1680097868.451917791]: /rtabmap/rtabmapviz: subscribe_scan = false
[ INFO] [1680097868.452060105]: /rtabmap/rtabmapviz: subscribe_scan_cloud = false
[ INFO] [1680097868.452200252]: /rtabmap/rtabmapviz: subscribe_scan_descriptor = false
[ INFO] [1680097868.452344065]: /rtabmap/rtabmapviz: queue_size    = 10
[ INFO] [1680097868.452489805]: /rtabmap/rtabmapviz: approx_sync   = true
[ INFO] [1680097868.452664840]: Setup depth callback
[ INFO] [1680097868.712318785]: 
/rtabmap/rtabmapviz subscribed to (approx sync):
   /odom \
   /camera/rgb/image_rect_color \
   /camera/depth_registered/image_raw \
   /camera/rgb/camera_info \
   /rtabmap/odom_info
[ INFO] [1680097868.712917447]: rtabmapviz started.
[ WARN] [1680097869.555629630]: /rtabmap/rtabmap: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/rtabmap/rtabmap subscribed to (approx sync):
   /odom \
   /camera/rgb/image_rect_color \
   /camera/depth_registered/image_raw \
   /camera/rgb/camera_info \
   /rtabmap/odom_info
[ WARN] [1680097873.017379654]: /rtabmap/rgbd_odometry: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. 
/rtabmap/rgbd_odometry subscribed to (approx sync):
   /camera/rgb/image_rect_color \
   /camera/depth_registered/image_raw \
   /camera/rgb/camera_info
[ WARN] [1680097873.713013828]: /rtabmap/rtabmapviz: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/rtabmap/rtabmapviz subscribed to (approx sync):
   /odom \
   /camera/rgb/image_rect_color \
   /camera/depth_registered/image_raw \
   /camera/rgb/camera_info \
   /rtabmap/odom_info

**Comment by Embedded1993** [comment]
I have checked topic also.

ubuntu@ubuntu:~$ rostopic hz odom /camera/rgb/image_rect_color  /camera/depth_registered/image_raw /camera/rgb/camera_info /rtabmap/odom_info
subscribed to [/odom]
subscribed to [/camera/rgb/image_rect_color]
subscribed to [/camera/depth_registered/image_raw]
subscribed to [/camera/rgb/camera_info]
subscribed to [/rtabmap/odom_info]
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages

**Comment by Serafadam** [comment]
Hi, you should remap topics in rtabmap launch (see the example launch file). Also a minor note - if you have a camera with autofocus enabled, that might cause issues with odometry at startup, to solve that you can either set reset odometry via service/in rtabmap gui or set manual focus for the camera driver.

**Comment by Embedded1993** [comment]
Thank you. how to remap topic in oak-d? 
I used it.
**roslaunch depthai_ros_driver rtabmap.launch**

Sorry my stupied question.

**Comment by Embedded1993** [comment]
I'm getting this error when run roslaunch **depthai_examples stereo_inertial_node.launch depth_aligned:=false**

[1844301011C2740E00] [1.1.2] [107.001] [system] [info] Cpu Usage - LeonOS 18.41%, LeonRT: 3.74%
[1844301011C2740E00] [1.1.2] [108.002] [system] [info] Memory Usage - DDR: 71.40 / 340.42 MiB, CMX: 2.09 / 2.50 MiB, LeonOS Heap: 36.16 / 77.32 MiB, LeonRT Heap: 4.13 / 41.23 MiB
[1844301011C2740E00] [1.1.2] [108.002] [system] [info] Temperatures - Average: 37.53 °C, CSS: 38.18 °C, MSS 36.77 °C, UPA: 37.71 °C, DSS: 37.48 °C
[1844301011C2740E00] [1.1.2] [108.002] [system] [info] Cpu Usage - LeonOS 19.67%, LeonRT: 4.30%
[2023-03-31 17:48:06.958] [warning] Monitor thread (device: 1844301011C2740E00 [1.1.2]) - **ping was missed, closing the device connection
[rviz-7] process has died [pid 51943, exit code -9, cmd /opt/ros/noetic/lib/rviz/rviz -d /home/ubuntu/work/dai_ws/src/depthai-ros/depthai_examples/rviz/stereoInertialROS1.rviz __name:=rviz __log:=/home/ubuntu/.ros/log/e35d4600-cfeb-11ed-9a8b-993cf8ad3baf/rviz-7.log].**
log file: /home/ubuntu/.ros/log/e35d4600-cfeb-11ed-9a8b-993cf8ad3baf/rviz-7*.log
[depth_image_to_pointcloud-6] process has finished cleanly
log file: /home/ubuntu/.ros/log/e35d4600-cfeb-11ed-9a8b-993cf8ad3baf/depth_image_to_pointcloud-6*.log
[depth_image_convertion_nodelet-5] process has finished cleanly
log file: /home/ubuntu/.ros/log/e35d4600-cfeb-11ed-9a8b-993cf8ad3baf/depth_image_convertion_nodelet-5*.log

I'm not sure why camera warn

![image](https://user-images.githubusercontent.com/98973485/229196356-5dec829a-fbf8-48d8-8ff5-08b53d391db3.png)

I saw this in master.log .
[rosmaster.master][INFO] 2023-03-31 17:48:07,863: publisherUpdate[/nodelet_manager/bond] -> http://ubuntu:33295/ ['http://ubuntu:34177/', 'http://ubuntu:42327/']: sec=0.00, exception=<Fault -1: 'publisherUpdate: unknown method name'>
[rosmaster.master][INFO] 2023-03-31 17:48:07,899: publisherUpdate[/nodelet_manager/bond] -> http://ubuntu:42327/ ['http://ubuntu:34177/', 'http://ubuntu:42327/']
[rosmaster.master][INFO] 2023-03-31 17:48:07,901: -SUB [/stereo_inertial_publisher/stereo/image] /nodelet_manager http://ubuntu:34177/
[rosmaster.master][INFO] 2023-03-31 17:48:07,903: -SUB [/stereo_inertial_publisher/stereo/camera_info] /nodelet_manager http://ubuntu:34177/
[rosmaster.master][INFO] 2023-03-31 17:48:07,908: publisherUpdate[/nodelet_manager/bond] -> http://ubuntu:42327/ ['http://ubuntu:34177/', 'http://ubuntu:42327/']: sec=0.01, result=[1, '', 0]
[rosmaster.threadpool][ERROR] 2023-03-31 17:48:08,369: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1169, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response
    return u.close()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'publisherUpdate: unknown method name'>

[rosmaster.master][INFO] 2023-03-31 17:48:09,682: -PUB [/stereo_inertial_publisher/stereo/image/theora/parameter_descriptions] /nodelet_manager http://ubuntu:34177/
[rosmaster.master][INFO] 2023-03-31 17:48:09,685: -PUB [/stereo_inertial_publisher/stereo/image/theora/parameter_updates] /nodelet_manager http://ubuntu:34177/
[rosmaster.master][INFO] 2023-03-31 17:48:09,688: -SERVICE [/stereo_inertial_publisher/stereo/image/theora/set_parameters] /nodelet_manager rosrpc://ubuntu:42385
[rosmaster.master][INFO] 2023-03-31 17:48:09,690: -SUB [/stereo_inertial_publisher/stereo/depth] /nodelet_manager http://ubuntu:34177/
[rosmaster.master][INFO] 2023-03-31 17:48:10,954: -PUB [/stereo_inertial_publisher/stereo/points] /nodelet_manager http://ubuntu:34177/
[rosmaster.master][INFO] 2023-03-31 17:48:10,958: -SUB [/nodelet_manager/bond] /nodelet_manager http://ubuntu:34177/
[rosmaster.master][INFO] 2023-03-31 17:48:10,967: -PUB [/nodelet_manager/bond] /nodelet_manager http://ubuntu:34177/
[rosmaster.master][INFO] 2023-03-31 17:48:10,990: publisherUpdate[/stereo_inertial_publisher/stereo/points] -> http://ubuntu:38161/ []
[rosmaster.master][INFO] 2023-03-31 17:48:11,000: publisherUpdate[/stereo_inertial_publisher/stereo/points] -> http://ubuntu:38161/ []: sec=0.01, exception=[Errno 22] Invalid argument
[rosmaster.threadpool][ERROR] 2023-03-31 17:48:11,018: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 22] Invalid argument
